name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - name: Install
        run: npm ci --prefer-offline
      - name: Format check
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
